# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mo_engage_notification_controller_api import MoEngageNotificationControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMoEngageNotificationControllerApi(unittest.TestCase):
    """MoEngageNotificationControllerApi unit test stubs"""

    def setUp(self):
        self.api = MoEngageNotificationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_segment_using_post(self):
        """Test case for add_segment_using_post

        addSegment  # noqa: E501
        """
        pass

    def test_fetch_all_segment_using_get(self):
        """Test case for fetch_all_segment_using_get

        fetchAllSegment  # noqa: E501
        """
        pass

    def test_fetch_analytics_data_using_post(self):
        """Test case for fetch_analytics_data_using_post

        fetchAnalyticsData  # noqa: E501
        """
        pass

    def test_fetch_cross_domains_using_get(self):
        """Test case for fetch_cross_domains_using_get

        fetchCrossDomains  # noqa: E501
        """
        pass

    def test_fetch_notification_list_using_get(self):
        """Test case for fetch_notification_list_using_get

        fetchNotificationList  # noqa: E501
        """
        pass

    def test_fetch_slug_names_using_get(self):
        """Test case for fetch_slug_names_using_get

        fetchSlugNames  # noqa: E501
        """
        pass

    def test_send_notification_using_post(self):
        """Test case for send_notification_using_post

        sendNotification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
