# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.page_compact import PageCompact  # noqa: E501
from swagger_client.rest import ApiException


class TestPageCompact(unittest.TestCase):
    """PageCompact unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPageCompact(self):
        """Test PageCompact"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.page_compact.PageCompact()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
