# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.auto_company_chart_controller_api import AutoCompanyChartControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAutoCompanyChartControllerApi(unittest.TestCase):
    """AutoCompanyChartControllerApi unit test stubs"""

    def setUp(self):
        self.api = AutoCompanyChartControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_company_chart_using_get(self):
        """Test case for add_company_chart_using_get

        addCompanyChart  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
