# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.utils_controller_api import UtilsControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilsControllerApi(unittest.TestCase):
    """UtilsControllerApi unit test stubs"""

    def setUp(self):
        self.api = UtilsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_remove_all_locks_using_get(self):
        """Test case for remove_all_locks_using_get

        removeAllLocks  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
