# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.report_controller_api import ReportControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestReportControllerApi(unittest.TestCase):
    """ReportControllerApi unit test stubs"""

    def setUp(self):
        self.api = ReportControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_generate_report_using_post(self):
        """Test case for generate_report_using_post

        generateReport  # noqa: E501
        """
        pass

    def test_get_report_subscription_using_get(self):
        """Test case for get_report_subscription_using_get

        getReportSubscription  # noqa: E501
        """
        pass

    def test_get_reports_using_get(self):
        """Test case for get_reports_using_get

        getReports  # noqa: E501
        """
        pass

    def test_save_report_subscription_using_put(self):
        """Test case for save_report_subscription_using_put

        saveReportSubscription  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
