# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.web_engage_notification_controller_api import WebEngageNotificationControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebEngageNotificationControllerApi(unittest.TestCase):
    """WebEngageNotificationControllerApi unit test stubs"""

    def setUp(self):
        self.api = WebEngageNotificationControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_fetch_analytics_data_using_post1(self):
        """Test case for fetch_analytics_data_using_post1

        fetchAnalyticsData  # noqa: E501
        """
        pass

    def test_fetch_applications_using_get(self):
        """Test case for fetch_applications_using_get

        fetchApplications  # noqa: E501
        """
        pass

    def test_fetch_notification_type_using_get(self):
        """Test case for fetch_notification_type_using_get

        fetchNotificationType  # noqa: E501
        """
        pass

    def test_fetch_segments_using_get(self):
        """Test case for fetch_segments_using_get

        fetchSegments  # noqa: E501
        """
        pass

    def test_fetch_tags_using_get(self):
        """Test case for fetch_tags_using_get

        fetchTags  # noqa: E501
        """
        pass

    def test_send_notification_using_post1(self):
        """Test case for send_notification_using_post1

        sendNotification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
