# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.wire_feeds_controller_api import WireFeedsControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWireFeedsControllerApi(unittest.TestCase):
    """WireFeedsControllerApi unit test stubs"""

    def setUp(self):
        self.api = WireFeedsControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_find_all_feeds_using_get(self):
        """Test case for find_all_feeds_using_get

        feeds  # noqa: E501
        """
        pass

    def test_find_all_images_using_get(self):
        """Test case for find_all_images_using_get

        feeds images  # noqa: E501
        """
        pass

    def test_find_all_story_using_get(self):
        """Test case for find_all_story_using_get

        findAllStory  # noqa: E501
        """
        pass

    def test_find_all_tech_images_using_get(self):
        """Test case for find_all_tech_images_using_get

        tech images  # noqa: E501
        """
        pass

    def test_find_all_wire_images_using_get(self):
        """Test case for find_all_wire_images_using_get

        findAllWireImages  # noqa: E501
        """
        pass

    def test_get_image_using_get(self):
        """Test case for get_image_using_get

        getImage  # noqa: E501
        """
        pass

    def test_get_stroy_using_get(self):
        """Test case for get_stroy_using_get

        getStroy  # noqa: E501
        """
        pass

    def test_get_wire_dashboard_search_suggestions_using_get(self):
        """Test case for get_wire_dashboard_search_suggestions_using_get

        getWireDashboardSearchSuggestions  # noqa: E501
        """
        pass

    def test_get_wire_feeds_using_get(self):
        """Test case for get_wire_feeds_using_get

        getWireFeeds  # noqa: E501
        """
        pass

    def test_get_wire_mint_feeds_using_get(self):
        """Test case for get_wire_mint_feeds_using_get

        getWireMintFeeds  # noqa: E501
        """
        pass

    def test_update_feed_story_using_put(self):
        """Test case for update_feed_story_using_put

        updateFeedStory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
