# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.footer_navigation import FooterNavigation  # noqa: E501
from swagger_client.rest import ApiException


class TestFooterNavigation(unittest.TestCase):
    """FooterNavigation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFooterNavigation(self):
        """Test FooterNavigation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.footer_navigation.FooterNavigation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
