# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AlternateSection(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'section': 'str',
        'subsection': 'str'
    }

    attribute_map = {
        'section': 'section',
        'subsection': 'subsection'
    }

    def __init__(self, section=None, subsection=None):  # noqa: E501
        """AlternateSection - a model defined in Swagger"""  # noqa: E501
        self._section = None
        self._subsection = None
        self.discriminator = None
        if section is not None:
            self.section = section
        if subsection is not None:
            self.subsection = subsection

    @property
    def section(self):
        """Gets the section of this AlternateSection.  # noqa: E501


        :return: The section of this AlternateSection.  # noqa: E501
        :rtype: str
        """
        return self._section

    @section.setter
    def section(self, section):
        """Sets the section of this AlternateSection.


        :param section: The section of this AlternateSection.  # noqa: E501
        :type: str
        """

        self._section = section

    @property
    def subsection(self):
        """Gets the subsection of this AlternateSection.  # noqa: E501


        :return: The subsection of this AlternateSection.  # noqa: E501
        :rtype: str
        """
        return self._subsection

    @subsection.setter
    def subsection(self, subsection):
        """Sets the subsection of this AlternateSection.


        :param subsection: The subsection of this AlternateSection.  # noqa: E501
        :type: str
        """

        self._subsection = subsection

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AlternateSection, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AlternateSection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
