# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class HowToStep(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'step': 'str',
        'step_image': 'Image'
    }

    attribute_map = {
        'step': 'step',
        'step_image': 'stepImage'
    }

    def __init__(self, step=None, step_image=None):  # noqa: E501
        """HowToStep - a model defined in Swagger"""  # noqa: E501
        self._step = None
        self._step_image = None
        self.discriminator = None
        if step is not None:
            self.step = step
        if step_image is not None:
            self.step_image = step_image

    @property
    def step(self):
        """Gets the step of this HowToStep.  # noqa: E501


        :return: The step of this HowToStep.  # noqa: E501
        :rtype: str
        """
        return self._step

    @step.setter
    def step(self, step):
        """Sets the step of this HowToStep.


        :param step: The step of this HowToStep.  # noqa: E501
        :type: str
        """

        self._step = step

    @property
    def step_image(self):
        """Gets the step_image of this HowToStep.  # noqa: E501


        :return: The step_image of this HowToStep.  # noqa: E501
        :rtype: Image
        """
        return self._step_image

    @step_image.setter
    def step_image(self, step_image):
        """Sets the step_image of this HowToStep.


        :param step_image: The step_image of this HowToStep.  # noqa: E501
        :type: Image
        """

        self._step_image = step_image

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HowToStep, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HowToStep):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
