# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MarketTopicUrl(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'domain': 'str',
        'name': 'str',
        'stock_id': 'str',
        'url': 'str'
    }

    attribute_map = {
        'domain': 'domain',
        'name': 'name',
        'stock_id': 'stockId',
        'url': 'url'
    }

    def __init__(self, domain=None, name=None, stock_id=None, url=None):  # noqa: E501
        """MarketTopicUrl - a model defined in Swagger"""  # noqa: E501
        self._domain = None
        self._name = None
        self._stock_id = None
        self._url = None
        self.discriminator = None
        if domain is not None:
            self.domain = domain
        if name is not None:
            self.name = name
        if stock_id is not None:
            self.stock_id = stock_id
        if url is not None:
            self.url = url

    @property
    def domain(self):
        """Gets the domain of this MarketTopicUrl.  # noqa: E501


        :return: The domain of this MarketTopicUrl.  # noqa: E501
        :rtype: str
        """
        return self._domain

    @domain.setter
    def domain(self, domain):
        """Sets the domain of this MarketTopicUrl.


        :param domain: The domain of this MarketTopicUrl.  # noqa: E501
        :type: str
        """

        self._domain = domain

    @property
    def name(self):
        """Gets the name of this MarketTopicUrl.  # noqa: E501


        :return: The name of this MarketTopicUrl.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this MarketTopicUrl.


        :param name: The name of this MarketTopicUrl.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def stock_id(self):
        """Gets the stock_id of this MarketTopicUrl.  # noqa: E501


        :return: The stock_id of this MarketTopicUrl.  # noqa: E501
        :rtype: str
        """
        return self._stock_id

    @stock_id.setter
    def stock_id(self, stock_id):
        """Sets the stock_id of this MarketTopicUrl.


        :param stock_id: The stock_id of this MarketTopicUrl.  # noqa: E501
        :type: str
        """

        self._stock_id = stock_id

    @property
    def url(self):
        """Gets the url of this MarketTopicUrl.  # noqa: E501


        :return: The url of this MarketTopicUrl.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this MarketTopicUrl.


        :param url: The url of this MarketTopicUrl.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MarketTopicUrl, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MarketTopicUrl):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
