# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TranslationWrapper(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'headline': 'str',
        'summary': 'str',
        'translation': 'list[Translation]'
    }

    attribute_map = {
        'headline': 'headline',
        'summary': 'summary',
        'translation': 'translation'
    }

    def __init__(self, headline=None, summary=None, translation=None):  # noqa: E501
        """TranslationWrapper - a model defined in Swagger"""  # noqa: E501
        self._headline = None
        self._summary = None
        self._translation = None
        self.discriminator = None
        if headline is not None:
            self.headline = headline
        if summary is not None:
            self.summary = summary
        if translation is not None:
            self.translation = translation

    @property
    def headline(self):
        """Gets the headline of this TranslationWrapper.  # noqa: E501


        :return: The headline of this TranslationWrapper.  # noqa: E501
        :rtype: str
        """
        return self._headline

    @headline.setter
    def headline(self, headline):
        """Sets the headline of this TranslationWrapper.


        :param headline: The headline of this TranslationWrapper.  # noqa: E501
        :type: str
        """

        self._headline = headline

    @property
    def summary(self):
        """Gets the summary of this TranslationWrapper.  # noqa: E501


        :return: The summary of this TranslationWrapper.  # noqa: E501
        :rtype: str
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this TranslationWrapper.


        :param summary: The summary of this TranslationWrapper.  # noqa: E501
        :type: str
        """

        self._summary = summary

    @property
    def translation(self):
        """Gets the translation of this TranslationWrapper.  # noqa: E501


        :return: The translation of this TranslationWrapper.  # noqa: E501
        :rtype: list[Translation]
        """
        return self._translation

    @translation.setter
    def translation(self, translation):
        """Sets the translation of this TranslationWrapper.


        :param translation: The translation of this TranslationWrapper.  # noqa: E501
        :type: list[Translation]
        """

        self._translation = translation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TranslationWrapper, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TranslationWrapper):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
