# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UrlBodyDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'article_id': 'int',
        'headline': 'str'
    }

    attribute_map = {
        'article_id': 'articleId',
        'headline': 'headline'
    }

    def __init__(self, article_id=None, headline=None):  # noqa: E501
        """UrlBodyDTO - a model defined in Swagger"""  # noqa: E501
        self._article_id = None
        self._headline = None
        self.discriminator = None
        if article_id is not None:
            self.article_id = article_id
        if headline is not None:
            self.headline = headline

    @property
    def article_id(self):
        """Gets the article_id of this UrlBodyDTO.  # noqa: E501


        :return: The article_id of this UrlBodyDTO.  # noqa: E501
        :rtype: int
        """
        return self._article_id

    @article_id.setter
    def article_id(self, article_id):
        """Sets the article_id of this UrlBodyDTO.


        :param article_id: The article_id of this UrlBodyDTO.  # noqa: E501
        :type: int
        """

        self._article_id = article_id

    @property
    def headline(self):
        """Gets the headline of this UrlBodyDTO.  # noqa: E501


        :return: The headline of this UrlBodyDTO.  # noqa: E501
        :rtype: str
        """
        return self._headline

    @headline.setter
    def headline(self, headline):
        """Sets the headline of this UrlBodyDTO.


        :param headline: The headline of this UrlBodyDTO.  # noqa: E501
        :type: str
        """

        self._headline = headline

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UrlBodyDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UrlBodyDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
