# coding: utf-8

"""
    CMS-Backend API

    This is API documentation of CMS-Backend  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: htdevteam@hindustantimes.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WireMetadata(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'authors': 'list[str]',
        'status': 'str',
        'url': 'str'
    }

    attribute_map = {
        'authors': 'authors',
        'status': 'status',
        'url': 'url'
    }

    def __init__(self, authors=None, status=None, url=None):  # noqa: E501
        """WireMetadata - a model defined in Swagger"""  # noqa: E501
        self._authors = None
        self._status = None
        self._url = None
        self.discriminator = None
        if authors is not None:
            self.authors = authors
        if status is not None:
            self.status = status
        if url is not None:
            self.url = url

    @property
    def authors(self):
        """Gets the authors of this WireMetadata.  # noqa: E501


        :return: The authors of this WireMetadata.  # noqa: E501
        :rtype: list[str]
        """
        return self._authors

    @authors.setter
    def authors(self, authors):
        """Sets the authors of this WireMetadata.


        :param authors: The authors of this WireMetadata.  # noqa: E501
        :type: list[str]
        """

        self._authors = authors

    @property
    def status(self):
        """Gets the status of this WireMetadata.  # noqa: E501


        :return: The status of this WireMetadata.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this WireMetadata.


        :param status: The status of this WireMetadata.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def url(self):
        """Gets the url of this WireMetadata.  # noqa: E501


        :return: The url of this WireMetadata.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this WireMetadata.


        :param url: The url of this WireMetadata.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WireMetadata, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WireMetadata):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
